update pkg

diff --git a/usr/bin/start-calamares b/usr/bin/start-calamares
--- a/usr/bin/start-calamares
+++ b/usr/bin/start-calamares
@@ -18,30 +18,43 @@ TOOL_NAME="Calamares Startup"
 
 export QT_QUICK_CONTROLS_STYLE=org.kde.breeze
 
+
 # -- Print messages to stderr.
 
-puts_info() {
-	if [ -n "$1" ]; then
-		printf "%s: \e[34mInfo:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
-	fi
+_puts() {
+    [ -n "${1-}" ] || return 0
+
+    level=$1
+    shift || true
+
+    [ $# -gt 0 ] || return 0
+
+    case "$level" in
+        info)    color='34'; label='Info' ;;
+        success) color='32'; label='Success' ;;
+        warning) color='33'; label='Warning' ;;
+        error)   color='31'; label='Error' ;;
+        *)       color='0';  label="$level" ;;
+    esac
+
+    if [ "$level" = "error" ]; then
+        printf '%s: \033[%sm%s:\033[0m %b\n' "${TOOL_NAME-}" "$color" "$label" "$*" >&2
+    else
+        printf '%s: \033[%sm%s:\033[0m %s\n' "${TOOL_NAME-}" "$color" "$label" "$*" >&2
+    fi
 }
 
+puts_info()    { _puts info "$@"; }
+puts_success() { _puts success "$@"; }
+puts_warning() { _puts warning "$@"; }
+puts_error()   { _puts error "$@"; }
 
-# -- Print success messages to stderr.
-
-puts_success() {
-	if [ -n "$1" ]; then
-		printf "%s: \e[32mSuccess:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
-	fi
-}
-
-
-# -- Print error messages to stderr.
-
-puts_error() {
-	if [ -n "$1" ]; then
-		printf "%s: \e[31mError:\e[0m %b\n" "$TOOL_NAME" "$*" >&2
-	fi
+print_message() {
+    if [ $# -eq 0 ]; then
+        printf '\n' >&2
+    else
+        printf '%s\n' "$@" >&2
+    fi
 }
 
 
